development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: interview_development
  pool: 5
  username: root
  password: zero50
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: interview_test
  pool: 5
  username: root
  password: zero50
  socket: /tmp/mysql.sock